server:
  port: 8081
  tomcat:
    uri-encoding: utf-8

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

translate:
  model:
    path: d:\data\models\
  language: en
  ans:
    suffix: .txt

ans:
  file:
    path: d:\data\speak\ans

tmp:
  file:
    path: d:\data\speak\tmp

txt:
  save:
    path: d:\data\speak\txt

audio:
  save:
    path: d:\data\speak\audio
    suffix: .wav

# 文件分隔符
File:
  split: \
